USE [master]
GO

/****** Object:  Database [DB_BELAJAR_SQL]    Script Date: 11/25/2021 3:29:25 AM ******/
CREATE DATABASE [DB_BELAJAR_SQL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_BELAJAR_SQL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_BELAJAR_SQL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_BELAJAR_SQL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_BELAJAR_SQL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_BELAJAR_SQL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET RECOVERY FULL 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET  MULTI_USER 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DB_BELAJAR_SQL] SET  READ_WRITE 
GO

